Install additional dependencies to fix errors when running tests.
Fixes the following errors:
ModuleNotFoundError: No module named 'flashlight'
RuntimeError: CTC Decoder suit requires flashlight-text package and optionally KenLM. Please install them.
SentencePiece is not available. Please install it.
DeepPhonemizer is not installed. Please install it.

Fixes the following tests:
test/integration_tests/ctc_decoder_integration_test.py
test/integration_tests/rnnt_pipeline_test.py
test/torchaudio_unittest/kaldi_io_test.py
test/torchaudio_unittest/models/decoder/ctc_decoder_test.py

Tested on both rocm and nvidia