Add additional guard to libsndfile
Summary:

Add additional check of libsndfile when soundfile is needed.
Background: https://github.com/pytorch/audio/issues/1687
No functional change

Test steps:
1. Setup
Install soundfile: $ pip install soundfile
delete libsndfile: $ with-proxy conda remove libsndfile

2. Repro the error
$python → >>> import torchaudio  → you would find an actionable error:
raise RuntimeError("""soundfile requires libsndfile to be installed. Try install it via:
RuntimeError: soundfile requires libsndfile to be installed. Try install it via:
$conda install -c conda-forge libsndfile

3. Fix the error
Follow error msg above to install libsndfile, and import torchaudio, it will succeed.

Test Plan:

Reviewers:

Subscribers:

Tasks:

Tags: